# -*- coding: utf-8 -*-
"""oxide-element.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FOfHh-hXgLW2TAxUEJvhD48Cy233rKe6

## So sweet!
"""

import streamlit as st

st.header('Enter an Oxide')